"""Create isolated, runnable Behave workspaces for E2EDev tests."""

from __future__ import annotations

import re
import shutil
from hashlib import sha256
from pathlib import Path

from .schemas import (
    ArtifactRef,
    Status,
    TestMaterializerInput,
    TestMaterializerOutput,
    WorkspaceSpec,
)


class MaterializationError(RuntimeError):
    """Raised when one test cannot be converted into a runnable workspace."""


_FILE_URL = re.compile(r"file://[^\"'\s)]+", re.IGNORECASE)
_FILE_PATH_ASSIGNMENT = re.compile(
    r"(?m)^(?P<prefix>\s*file_path\s*=\s*)(?P<quote>['\"])(?P<value>[^'\"]+)(?P=quote)"
)


_ENVIRONMENT_PY = '''"""Runtime hooks generated by test-evaluator."""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path


_BROWSER_TRACE_SCRIPT = r"""
(() => {
  if (window.__testEvaluatorTrace) return;
  const stubs = new Set(__TEST_EVALUATOR_STUBS__);
  const trace = {storage: [], network: [], browser_api: []};
  Object.defineProperty(window, "__testEvaluatorTrace", {value: trace, configurable: true});
  const clean = (value) => {
    if (value === undefined) return null;
    if (value === null || ["string", "number", "boolean"].includes(typeof value)) return value;
    try { return JSON.parse(JSON.stringify(value)); } catch (_) { return String(value); }
  };
  const push = (kind, operation, detail = {}) => {
    trace[kind].push({timestamp: Date.now(), operation, ...clean(detail)});
  };

  for (const method of ["setItem", "getItem", "removeItem", "clear"]) {
    const original = Storage.prototype[method];
    if (!original) continue;
    Storage.prototype[method] = function(...args) {
      const area = this === window.localStorage ? "localStorage" : "sessionStorage";
      push("storage", method, {area, key: clean(args[0]), value: clean(args[1])});
      return original.apply(this, args);
    };
  }

  if (window.fetch) {
    const originalFetch = window.fetch.bind(window);
    window.fetch = function(input, init = {}) {
      const url = typeof input === "string" ? input : input?.url;
      push("network", "fetch", {url, method: init.method || "GET"});
      if (stubs.has("network") && /^https?:/i.test(url || "")) {
        push("network", "fetch_stubbed", {url});
        return Promise.resolve(new Response("{}", {status: 503, headers: {"Content-Type": "application/json"}}));
      }
      return originalFetch(input, init);
    };
  }

  if (window.XMLHttpRequest) {
    const originalOpen = XMLHttpRequest.prototype.open;
    const originalSend = XMLHttpRequest.prototype.send;
    XMLHttpRequest.prototype.open = function(method, url, ...rest) {
      this.__testEvaluatorRequest = {method, url};
      return originalOpen.call(this, method, url, ...rest);
    };
    XMLHttpRequest.prototype.send = function(body) {
      push("network", "xhr", {...(this.__testEvaluatorRequest || {}), body: clean(body)});
      if (stubs.has("network") && /^https?:/i.test(this.__testEvaluatorRequest?.url || "")) {
        push("network", "xhr_stub_requested", this.__testEvaluatorRequest || {});
      }
      return originalSend.call(this, body);
    };
  }

  const speech = window.speechSynthesis;
  if (speech?.speak) {
    const originalSpeak = speech.speak.bind(speech);
    speech.speak = function(utterance) {
      push("browser_api", "speechSynthesis.speak", {text: utterance?.text || ""});
      if (!stubs.has("speech")) return originalSpeak(utterance);
    };
  }
  const clipboard = navigator.clipboard;
  if (clipboard?.writeText) {
    const originalWrite = clipboard.writeText.bind(clipboard);
    clipboard.writeText = function(text) {
      push("browser_api", "clipboard.writeText", {text});
      return stubs.has("clipboard") ? Promise.resolve() : originalWrite(text);
    };
  }
  if (window.Notification?.requestPermission) {
    const originalPermission = Notification.requestPermission.bind(Notification);
    Notification.requestPermission = function(...args) {
      push("browser_api", "Notification.requestPermission", {});
      return stubs.has("notification") ? Promise.resolve("denied") : originalPermission(...args);
    };
  }
})();
"""


def _write_coverage(driver):
    method = os.environ.get("TEST_EVALUATOR_COVERAGE_METHOD", "none")
    if method == "istanbul":
        if getattr(driver, "_test_evaluator_coverage_written", False):
            return
        try:
            result = driver.execute_script("return window.__coverage__ || {};")
            artifacts = Path(os.environ["TEST_EVALUATOR_ARTIFACTS"])
            artifacts.mkdir(parents=True, exist_ok=True)
            (artifacts / "istanbul_coverage.json").write_text(
                json.dumps(result, indent=2), encoding="utf-8"
            )
            driver._test_evaluator_coverage_written = True
        except Exception:
            pass
        return
    if not getattr(driver, "_test_evaluator_coverage_started", False):
        return
    if getattr(driver, "_test_evaluator_coverage_written", False):
        return
    try:
        result = driver.execute_cdp_cmd("Profiler.takePreciseCoverage", {})
        artifacts = Path(os.environ["TEST_EVALUATOR_ARTIFACTS"])
        artifacts.mkdir(parents=True, exist_ok=True)
        (artifacts / "coverage.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
        driver._test_evaluator_coverage_written = True
    except Exception:
        pass
    finally:
        try:
            driver.execute_cdp_cmd("Profiler.stopPreciseCoverage", {})
            driver.execute_cdp_cmd("Profiler.disable", {})
        except Exception:
            pass


def _write_observability(driver):
    if getattr(driver, "_test_evaluator_observability_written", False):
        return
    artifacts = Path(os.environ["TEST_EVALUATOR_ARTIFACTS"])
    artifacts.mkdir(parents=True, exist_ok=True)
    try:
        result = driver.execute_script("return window.__testEvaluatorTrace || null;")
        if result is not None:
            (artifacts / "browser_trace.json").write_text(
                json.dumps(result, indent=2), encoding="utf-8"
            )
    except Exception:
        pass
    try:
        raw_logs = driver.get_log("performance")
        network_logs = []
        for item in raw_logs:
            try:
                message = json.loads(item.get("message", "{}"))
                event = message.get("message", {})
                if str(event.get("method", "")).startswith("Network."):
                    network_logs.append(event)
            except Exception:
                continue
        if network_logs:
            (artifacts / "network_log.json").write_text(
                json.dumps(network_logs, indent=2), encoding="utf-8"
            )
    except Exception:
        pass
    driver._test_evaluator_observability_written = True


def before_all(context):
    from selenium import webdriver
    from selenium.webdriver.chrome.service import Service

    original_chrome = webdriver.Chrome

    def managed_chrome(*args, **kwargs):
        # E2EDev tests normally call webdriver.Chrome() without options. Preserve
        # explicit caller arguments, but make the common path deterministic on
        # CI/Linux by selecting the installed browser and matching driver.
        if not args:
            options = kwargs.get("options")
            if options is None:
                options = webdriver.ChromeOptions()
                kwargs["options"] = options
            if not options.binary_location:
                chrome_binary = shutil.which("google-chrome") or shutil.which("chromium")
                if chrome_binary:
                    options.binary_location = chrome_binary
            if os.environ.get("TEST_EVALUATOR_HEADLESS", "1") == "1":
                for argument in (
                    "--headless=new",
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--window-size=1920,1080",
                    "--allow-file-access-from-files",
                ):
                    options.add_argument(argument)
            if os.environ.get("TEST_EVALUATOR_OBSERVABILITY", "1") == "1":
                options.set_capability(
                    "goog:loggingPrefs", {"browser": "ALL", "performance": "ALL"}
                )
            if kwargs.get("service") is None:
                driver_binary = shutil.which("chromedriver")
                if driver_binary:
                    kwargs["service"] = Service(driver_binary)
        driver = original_chrome(*args, **kwargs)
        if os.environ.get("TEST_EVALUATOR_OBSERVABILITY", "1") == "1":
            try:
                stubs = [
                    item.strip()
                    for item in os.environ.get("TEST_EVALUATOR_BROWSER_STUBS", "").split(",")
                    if item.strip()
                ]
                source = _BROWSER_TRACE_SCRIPT.replace(
                    "__TEST_EVALUATOR_STUBS__", json.dumps(stubs)
                )
                driver.execute_cdp_cmd(
                    "Page.addScriptToEvaluateOnNewDocument", {"source": source}
                )
            except Exception:
                pass
        if os.environ.get("TEST_EVALUATOR_COVERAGE_METHOD") == "cdp_precise_coverage":
            try:
                driver.execute_cdp_cmd("Profiler.enable", {})
                driver.execute_cdp_cmd(
                    "Profiler.startPreciseCoverage",
                    {"callCount": True, "detailed": True, "allowTriggeredUpdates": False},
                )
                driver._test_evaluator_coverage_started = True
            except Exception:
                pass
        original_quit = driver.quit

        def quit_with_artifacts():
            _write_coverage(driver)
            _write_observability(driver)
            return original_quit()

        driver.quit = quit_with_artifacts
        return driver

    webdriver.Chrome = managed_chrome


def after_step(context, step):
    if str(getattr(step, "status", "")).casefold() not in {
        "failed",
        "status.failed",
        "error",
        "status.error",
    }:
        return
    driver = getattr(context, "driver", None)
    if driver is None:
        return
    artifacts = Path(os.environ["TEST_EVALUATOR_ARTIFACTS"])
    artifacts.mkdir(parents=True, exist_ok=True)
    try:
        driver.save_screenshot(str(artifacts / "failure.png"))
    except Exception:
        pass
    try:
        (artifacts / "dom_snapshot.html").write_text(driver.page_source, encoding="utf-8")
    except Exception:
        pass
    try:
        logs = driver.get_log("browser")
        (artifacts / "console_log.json").write_text(json.dumps(logs, indent=2), encoding="utf-8")
    except Exception:
        pass


def after_scenario(context, scenario):
    driver = getattr(context, "driver", None)
    if driver is not None:
        try:
            _write_coverage(driver)
            _write_observability(driver)
            driver.quit()
        except Exception:
            pass
'''


def _safe_segment(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("._")
    return cleaned[:64] or "test"


def _workspace_name(record_key: str) -> str:
    digest = sha256(record_key.encode("utf-8")).hexdigest()[:10]
    return f"{_safe_segment(record_key)}-{digest}"


def _entry_path(inventory_source: Path, app_root: Path, entry_html: str | None) -> Path:
    if not entry_html:
        raise MaterializationError("No HTML entry point was discovered for this project")
    relative = Path(entry_html)
    if relative.is_absolute() or ".." in relative.parts:
        raise MaterializationError(f"Unsafe entry HTML path: {entry_html}")
    source_entry = (inventory_source / relative).resolve()
    try:
        source_entry.relative_to(inventory_source.resolve())
    except ValueError as error:
        raise MaterializationError(f"Entry HTML escapes source root: {entry_html}") from error
    if not source_entry.is_file():
        raise MaterializationError(f"Entry HTML does not exist: {source_entry}")
    return (app_root / relative).resolve()


def _rewrite_step_paths(step_code: str, entry_html: Path) -> tuple[str, list[dict[str, str]]]:
    rewritten = step_code
    changes: list[dict[str, str]] = []
    entry_uri = entry_html.as_uri()

    def replace_url(match: re.Match[str]) -> str:
        original = match.group(0)
        if original != entry_uri:
            changes.append({"kind": "file_url", "original": original, "replacement": entry_uri})
        return entry_uri

    rewritten = _FILE_URL.sub(replace_url, rewritten)

    def replace_assignment(match: re.Match[str]) -> str:
        original_value = match.group("value")
        replacement = str(entry_html)
        if original_value != replacement:
            changes.append(
                {
                    "kind": "file_path_assignment",
                    "original": original_value,
                    "replacement": replacement,
                }
            )
        quote = match.group("quote")
        return f"{match.group('prefix')}{quote}{replacement}{quote}"

    rewritten = _FILE_PATH_ASSIGNMENT.sub(replace_assignment, rewritten)
    return rewritten, changes


def materialize_test(request: TestMaterializerInput) -> TestMaterializerOutput:
    """Copy application source and write one feature/steps pair without touching the clone."""

    inventory = request.inventory
    record = request.record
    if inventory.project_id != record.project_id:
        raise MaterializationError(
            f"Inventory project {inventory.project_id!r} does not match record project {record.project_id!r}"
        )
    if not record.scenario.strip():
        raise MaterializationError("The test has no Gherkin scenario")
    if not record.step_code.strip():
        raise MaterializationError("The test has no Behave step implementation")
    if not inventory.source_root:
        raise MaterializationError("The project has no discovered source root")

    source_root = Path(inventory.source_root).resolve()
    if not source_root.is_dir():
        raise MaterializationError(f"Source root does not exist: {source_root}")

    workspace_root = Path(request.output_dir).resolve() / _workspace_name(record.record_key)
    app_root = workspace_root / "app"
    features_root = workspace_root / "features"
    steps_root = features_root / "steps"
    artifacts_dir = workspace_root / "artifacts"
    if workspace_root.exists():
        shutil.rmtree(workspace_root)
    workspace_root.mkdir(parents=True)
    shutil.copytree(
        source_root,
        app_root,
        ignore=shutil.ignore_patterns(".DS_Store", "__pycache__", "*.pyc"),
    )
    steps_root.mkdir(parents=True)
    artifacts_dir.mkdir(parents=True)

    entry_html = _entry_path(source_root, app_root, inventory.entry_html)
    feature_file = features_root / "test.feature"
    steps_file = steps_root / "steps.py"
    environment_file = features_root / "environment.py"
    rewritten_code, rewritten_paths = _rewrite_step_paths(record.step_code, entry_html)

    feature_file.write_text(record.scenario.rstrip() + "\n", encoding="utf-8")
    steps_file.write_text(rewritten_code.rstrip() + "\n", encoding="utf-8")
    environment_file.write_text(_ENVIRONMENT_PY, encoding="utf-8")

    workspace = WorkspaceSpec(
        record_key=record.record_key,
        workspace_root=str(workspace_root),
        app_root=str(app_root),
        feature_file=str(feature_file),
        steps_file=str(steps_file),
        entry_html=str(entry_html),
        artifacts_dir=str(artifacts_dir),
        rewritten_paths=rewritten_paths,
    )
    return TestMaterializerOutput(
        agent="test_materializer",
        run_id=request.run_id,
        mode="full",
        project_id=record.project_id,
        suite_key=record.suite_key,
        record_key=record.record_key,
        status=Status.PASS,
        confidence=1.0,
        workspace=workspace,
        artifacts=[
            ArtifactRef(
                kind="workspace",
                path=str(workspace_root),
                description="Isolated Behave/Selenium workspace",
            )
        ],
    )
